version: "2"

services:
  map-tiles:
    build: .
    container_name: map-tiles-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
