version: "2"

services:
  here-proxy:
    build: .
    container_name: here-proxy-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
